/*
 Navicat Premium Data Transfer

 Source Server         : erwef
 Source Server Type    : Oracle
 Source Server Version : 110200
 Source Schema         : DIGITAL

 Target Server Type    : Oracle
 Target Server Version : 110200
 File Encoding         : 65001

 Date: 31/05/2025 00:35:57
*/


-- ----------------------------
-- Table structure for BILLPART
-- ----------------------------
DROP TABLE "DIGITAL"."BILLPART";
CREATE TABLE "DIGITAL"."BILLPART" (
  "LAST" VARCHAR2(20 BYTE),
  "DAYS_NO" VARCHAR2(20 BYTE),
  "EX" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CANCELLED
-- ----------------------------
DROP TABLE "DIGITAL"."CANCELLED";
CREATE TABLE "DIGITAL"."CANCELLED" (
  "RECEIPT_NO" VARCHAR2(20 BYTE),
  "STATUS" VARCHAR2(20 BYTE),
  "CANCEL_DATE" DATE,
  "CANCEL_TIME" VARCHAR2(20 BYTE),
  "CANCELLED_BY" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for CLIST
-- ----------------------------
DROP TABLE "DIGITAL"."CLIST";
CREATE TABLE "DIGITAL"."CLIST" (
  "COMPLAINT_NAME" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for COMPLAINT
-- ----------------------------
DROP TABLE "DIGITAL"."COMPLAINT";
CREATE TABLE "DIGITAL"."COMPLAINT" (
  "CNAME" VARCHAR2(20 BYTE),
  "CONTACT_NO" NUMBER(10,0),
  "PHONE_MODEL" VARCHAR2(20 BYTE),
  "COMPLAINT_NAME" VARCHAR2(20 BYTE),
  "RECVD_ACCR" VARCHAR2(200 BYTE),
  "RECVD_BY" VARCHAR2(20 BYTE),
  "RECEIPT_NO" VARCHAR2(20 BYTE),
  "RECVD_DATE" DATE,
  "EST_CHARGS" NUMBER(9,0),
  "RECVD_TIME" VARCHAR2(20 BYTE),
  "IMEI_NO" NUMBER(15,0),
  "ASSIGNED_TO" VARCHAR2(20 BYTE),
  "IMAGE_NAMES" VARCHAR2(200 BYTE),
  "EMAIL" VARCHAR2(20 BYTE),
  "ADVANCE" NUMBER DEFAULT 0,
  "BALANCE" NUMBER DEFAULT 0
   
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for DELIVERY
-- ----------------------------
DROP TABLE "DIGITAL"."DELIVERY";
CREATE TABLE "DIGITAL"."DELIVERY" (
  "RECEIPT_NO" VARCHAR2(20 BYTE),
  "DELIVERY_DATE" DATE,
  "AMOUNT" NUMBER(9,0),
  "ISSUED_BY" VARCHAR2(20 BYTE),
  "DELIVERY_TIME" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for EXTRACHARGES
-- ----------------------------
DROP TABLE "DIGITAL"."EXTRACHARGES";
CREATE TABLE "DIGITAL"."EXTRACHARGES" (
  "SERVICEID" VARCHAR2(20 BYTE),
  "CHARGES" NUMBER,
  "RDATE" DATE,
  "RTIME" VARCHAR2(20 BYTE),
  "COMPLAINT" VARCHAR2(200 BYTE),
  "RECVDBY" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for PAYMENTS
-- ----------------------------
DROP TABLE "DIGITAL"."PAYMENTS";
CREATE TABLE "DIGITAL"."PAYMENTS" (
  "SERVICEID" VARCHAR2(20 BYTE),
  "RECEIVED_AMOUNT" NUMBER(8,0),
  "TYPE" VARCHAR2(20 BYTE),
  "RECEIVED_DATE" DATE,
  "RECIEVED_TIME" VARCHAR2(20 BYTE),
  "RECEIVED_BY" VARCHAR2(20 BYTE),
  "CASHMODE" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for STATUS
-- ----------------------------
DROP TABLE "DIGITAL"."STATUS";
CREATE TABLE "DIGITAL"."STATUS" (
  "RECEIPT_NO" VARCHAR2(20 BYTE),
  "REMARKS" VARCHAR2(20 BYTE),
  "STATUS" VARCHAR2(20 BYTE),
  "STATUS_DATE" DATE,
  "DELIVERY_STATUS" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for TECHNICIAN
-- ----------------------------
DROP TABLE "DIGITAL"."TECHNICIAN";
CREATE TABLE "DIGITAL"."TECHNICIAN" (
  "USERID" VARCHAR2(20 BYTE),
  "PASSWD" VARCHAR2(20 BYTE),
  "FULL_NAME" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Table structure for USERS
-- ----------------------------
DROP TABLE "DIGITAL"."USERS";
CREATE TABLE "DIGITAL"."USERS" (
  "USERID" VARCHAR2(20 BYTE),
  "PASSWD" VARCHAR2(20 BYTE),
  "USER_TYPE" VARCHAR2(20 BYTE)
)
LOGGING
NOCOMPRESS
PCTFREE 10
INITRANS 1
STORAGE (
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1
  MAXEXTENTS 2147483645
  FREELISTS 1
  FREELIST GROUPS 1
  BUFFER_POOL DEFAULT
)
PARALLEL 1
NOCACHE
DISABLE ROW MOVEMENT
;

-- ----------------------------
-- Triggers structure for table COMPLAINT
-- ----------------------------
CREATE TRIGGER "DIGITAL"."TRG_INSERT_MOBILE_REPAIRS" AFTER INSERT ON "DIGITAL"."COMPLAINT" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
  v_count NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_count
  FROM DIGITAL1.MOBILE_REPAIRS
  WHERE REPAIR_ID = TO_NUMBER(:NEW.RECEIPT_NO);

  IF v_count = 0 THEN
    INSERT INTO DIGITAL1.MOBILE_REPAIRS (
      REPAIR_ID, DEVICE_MODEL, CUSTOMER_NAME, STATUS, REPAIR_DATE
    ) VALUES (
      TO_NUMBER(:NEW.RECEIPT_NO),
      :NEW.PHONE_MODEL,
      :NEW.CNAME,
      'NEW',
      SYSDATE
    );
  END IF;
END;
/

-- ----------------------------
-- Triggers structure for table STATUS
-- ----------------------------
CREATE TRIGGER "DIGITAL"."TRG_UPDATE_REPAIR_STATUS" AFTER INSERT OR UPDATE ON "DIGITAL"."STATUS" REFERENCING OLD AS "OLD" NEW AS "NEW" FOR EACH ROW 
DECLARE
  v_final_status VARCHAR2(255);
BEGIN
  v_final_status := CASE 
    WHEN :NEW.DELIVERY_STATUS IS NOT NULL 
         AND UPPER(:NEW.DELIVERY_STATUS) <> 'NO' 
    THEN :NEW.STATUS || ' [' || :NEW.DELIVERY_STATUS || ']'
    ELSE :NEW.STATUS
  END;

  UPDATE DIGITAL1.MOBILE_REPAIRS
  SET STATUS = v_final_status
  WHERE REPAIR_ID = TO_NUMBER(:NEW.RECEIPT_NO);

  UPDATE DIGITAL1.SUPPLIER_PAYMENTS
  SET REPAIR_STATUS = v_final_status
  WHERE REPAIR_ID = TO_NUMBER(:NEW.RECEIPT_NO);
END;
/
